var data = {
    "state": "0",
    "message": "",
    "data": [{
        "id": "1",
        "title": "姓  名",
        "tip": "",
        "sort": "10",
        "theme": "个人资料",
        "type": "essay",
        "parentId": "",
        "condition": "",
        "specialTipsPath": "",
        "answers": [],
        "isShow": "true"
    },
    {
        "id": "2",
        "title": "性  别",
        "tip": "",
        "sort": "20",
        "theme": "个人资料",
        "type": "single",
        "parentId": "",
        "condition": "",
        "specialTipsPath": "",
        "answers": [{
            "id": "7",
            "subjectId": "2",
            "answer": "男",
            "sex": "all",
            "number": "0",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "39+81+82+112+145+203+233+234+235+236+240+241+373+414",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": "linkHid:\"122a-127a-128a-130a-184a-185a\""
        },
        {
            "id": "8",
            "subjectId": "2",
            "answer": "女",
            "sex": "all",
            "number": "1",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "110+111+186+227+228+229+230+231",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": "23+24+30+31+55+56"
        }],
        "isShow": "true"
    },
    {
        "id": "3",
        "title": "年  龄",
        "tip": "",
        "sort": "30",
        "theme": "个人资料",
        "type": "essay",
        "parentId": "",
        "condition": "",
        "specialTipsPath": "",
        "answers": [{
            "id": "705",
            "subjectId": "3",
            "answer": "0-5",
            "sex": "all",
            "number": "0",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "2+312+56+57+58+149+208+278+281+291+321+322+323+324+325+326+327+348+167+364+286+10+319+149+73+167+346+239+126+127+124+125+10+286+342",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "706",
            "subjectId": "3",
            "answer": "6-10",
            "sex": "all",
            "number": "1",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "2+312+56+57+58+149+208+278+281+291+321+322+323+324+325+326+327+348+167+364+286+10+319+149+73+167+346+239+126+127+124+125+10+286+342",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "707",
            "subjectId": "3",
            "answer": "11-15",
            "sex": "all",
            "number": "2",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "2+312+56+57+58+149+208+278+281+291+321+322+323+324+325+326+327+348+167+364+286+10+319+149+73+167+346+239+126+127+124+125+10+286+342",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "708",
            "subjectId": "3",
            "answer": "16-20",
            "sex": "all",
            "number": "3",
            "content": "",
            "ordinaryLink": "2+312+56+57+58+149+208+278+281+291+321+322+323+324+325+326+327+348+167+364+286+10+319+149+73+167+346+239+126+127+124+125+10+286+342",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "709",
            "subjectId": "3",
            "answer": "21-25",
            "sex": "all",
            "number": "4",
            "content": "",
            "ordinaryLink": "2+312+56+57+58+149+208+278+281+291+321+322+323+324+325+326+327+348+167+364+286+10+319+149+73+167+346+239+126+127+124+125+10+286+342",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "710",
            "subjectId": "3",
            "answer": "26-30",
            "sex": "all",
            "number": "5",
            "content": "",
            "ordinaryLink": "2+312+56+57+58+149+208+278+281+291+321+322+323+324+325+326+327+348+167+364+286+10+319+149+73+167+346+239+126+127+124+125+10+286+342",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "711",
            "subjectId": "3",
            "answer": "31-35",
            "sex": "all",
            "number": "6",
            "content": "",
            "ordinaryLink": "2+312+56+57+58+149+208+278+281+291+321+322+323+324+325+326+327+348+167+364+286+10+319+149+73+167+346+239+126+127+124+125+10+286+342",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "712",
            "subjectId": "3",
            "answer": "36-40",
            "sex": "all",
            "number": "7",
            "content": "",
            "ordinaryLink": "2+312+56+57+58+149+208+278+281+291+321+322+323+324+325+326+327+348+167+364+286+10+319+149+73+167+346+239+126+127+124+125+10+286+342",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "713",
            "subjectId": "3",
            "answer": "41-45",
            "sex": "all",
            "number": "8",
            "content": "",
            "ordinaryLink": "2+312+56+57+58+149+208+278+281+291+321+322+323+324+325+326+327+348+167+364+286+10+319+149+73+167+346+239+126+127+124+125+10+286+342",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "714",
            "subjectId": "3",
            "answer": "46-50",
            "sex": "all",
            "number": "9",
            "content": "",
            "ordinaryLink": "2+312+56+57+58+149+208+278+281+291+321+322+323+324+325+326+327+348+167+364+286+10+319+149+73+167+346+239+126+127+124+125+10+286+342",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "715",
            "subjectId": "3",
            "answer": "51-55",
            "sex": "all",
            "number": "10",
            "content": "",
            "ordinaryLink": "2+312+56+57+58+149+208+278+281+291+321+322+323+324+325+326+327+348+167+364+286+10+319+149+73+167+346+239+126+127+124+125+10+286+342",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "716",
            "subjectId": "3",
            "answer": "56-60",
            "sex": "all",
            "number": "11",
            "content": "",
            "ordinaryLink": "2+312+56+57+58+149+208+278+281+291+321+322+323+324+325+326+327+348+167+364+286+10+319+149+73+167+346+239+126+127+124+125+10+286+342",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "717",
            "subjectId": "3",
            "answer": "61-65",
            "sex": "all",
            "number": "12",
            "content": "",
            "ordinaryLink": "2+312+56+57+58+149+208+278+281+291+321+322+323+324+325+326+327+348+167+364+286+10+319+149+73+167+346+239+126+127+124+125+10+286+342",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "718",
            "subjectId": "3",
            "answer": "66-70",
            "sex": "all",
            "number": "13",
            "content": "",
            "ordinaryLink": "2+312+56+57+58+149+208+278+281+291+321+322+323+324+325+326+327+348+167+364+286+10+319+149+73+167+346+239+126+127+124+125+10+286+342",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "719",
            "subjectId": "3",
            "answer": "71-75",
            "sex": "all",
            "number": "14",
            "content": "",
            "ordinaryLink": "2+312+56+57+58+149+208+278+281+291+321+322+323+324+325+326+327+348+167+364+286+10+319+149+73+167+346+239+126+127+124+125+10+286+342",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "720",
            "subjectId": "3",
            "answer": "76-80",
            "sex": "all",
            "number": "15",
            "content": "",
            "ordinaryLink": "2+312+56+57+58+149+208+278+281+291+321+322+323+324+325+326+327+348+167+364+286+10+319+149+73+167+346+239+126+127+124+125+10+286+342",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "721",
            "subjectId": "3",
            "answer": "81-1000",
            "sex": "all",
            "number": "16",
            "content": "",
            "ordinaryLink": "2+312+56+57+58+149+208+278+281+291+321+322+323+324+325+326+327+348+167+364+286+10+319+149+73+167+346+239+126+127+124+125+10+286+342",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        }],
        "isShow": "true"
    },
    {
        "id": "4",
        "title": "身份证号",
        "tip": "",
        "sort": "40",
        "theme": "个人资料",
        "type": "essay",
        "parentId": "",
        "condition": "",
        "specialTipsPath": "",
        "answers": [],
        "isShow": "true"
    },
    {
        "id": "5",
        "title": "民  族",
        "tip": "",
        "sort": "50",
        "theme": "个人资料",
        "type": "single",
        "parentId": "",
        "condition": "",
        "specialTipsPath": "",
        "answers": [{
            "id": "9",
            "subjectId": "5",
            "answer": "汉族",
            "sex": "all",
            "number": "0",
            "content": "",
            "ordinaryLink": "2+39+81+82+3",
            "accurateLink": "39+81+82",
            "depthLink": "39+81+82",
            "nolink": "1",
            "diseaseRisk": "33333",
            "riskFactors": "4444",
            "disease": "",
            "condition": ""
        },
        {
            "id": "10",
            "subjectId": "5",
            "answer": "蒙古族",
            "sex": "all",
            "number": "1",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "11",
            "subjectId": "5",
            "answer": "回族",
            "sex": "all",
            "number": "2",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "12",
            "subjectId": "5",
            "answer": "藏族",
            "sex": "all",
            "number": "3",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "13",
            "subjectId": "5",
            "answer": "维吾尔族",
            "sex": "all",
            "number": "4",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "14",
            "subjectId": "5",
            "answer": "苗族",
            "sex": "all",
            "number": "5",
            "content": "",
            "ordinaryLink": "9",
            "accurateLink": "",
            "depthLink": "1+30",
            "nolink": "1",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "15",
            "subjectId": "5",
            "answer": "彝族",
            "sex": "all",
            "number": "6",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "16",
            "subjectId": "5",
            "answer": "壮族",
            "sex": "all",
            "number": "7",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "17",
            "subjectId": "5",
            "answer": "布依族",
            "sex": "all",
            "number": "8",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "18",
            "subjectId": "5",
            "answer": "朝鲜族",
            "sex": "all",
            "number": "9",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "19",
            "subjectId": "5",
            "answer": "满族",
            "sex": "all",
            "number": "10",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "20",
            "subjectId": "5",
            "answer": "侗族",
            "sex": "all",
            "number": "11",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "21",
            "subjectId": "5",
            "answer": "瑶族",
            "sex": "all",
            "number": "12",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "22",
            "subjectId": "5",
            "answer": "白族",
            "sex": "all",
            "number": "13",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "23",
            "subjectId": "5",
            "answer": "土家族",
            "sex": "all",
            "number": "14",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "24",
            "subjectId": "5",
            "answer": "哈尼族",
            "sex": "all",
            "number": "15",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "25",
            "subjectId": "5",
            "answer": "哈萨克族",
            "sex": "all",
            "number": "16",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "26",
            "subjectId": "5",
            "answer": "傣族",
            "sex": "all",
            "number": "17",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "27",
            "subjectId": "5",
            "answer": "黎族",
            "sex": "all",
            "number": "18",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "28",
            "subjectId": "5",
            "answer": "傈僳族",
            "sex": "all",
            "number": "19",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "29",
            "subjectId": "5",
            "answer": "佤族",
            "sex": "all",
            "number": "20",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "30",
            "subjectId": "5",
            "answer": "畲族",
            "sex": "all",
            "number": "21",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "31",
            "subjectId": "5",
            "answer": "高山族",
            "sex": "all",
            "number": "22",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "32",
            "subjectId": "5",
            "answer": "拉祜族",
            "sex": "all",
            "number": "23",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "33",
            "subjectId": "5",
            "answer": "水族",
            "sex": "all",
            "number": "24",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "34",
            "subjectId": "5",
            "answer": "东乡族",
            "sex": "all",
            "number": "25",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "35",
            "subjectId": "5",
            "answer": "纳西族",
            "sex": "all",
            "number": "26",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "36",
            "subjectId": "5",
            "answer": "景颇族",
            "sex": "all",
            "number": "27",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "37",
            "subjectId": "5",
            "answer": "柯尔克孜族",
            "sex": "all",
            "number": "28",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "38",
            "subjectId": "5",
            "answer": "土族",
            "sex": "all",
            "number": "29",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "39",
            "subjectId": "5",
            "answer": "达斡尔族",
            "sex": "all",
            "number": "30",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "40",
            "subjectId": "5",
            "answer": "仫佬族",
            "sex": "all",
            "number": "31",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "41",
            "subjectId": "5",
            "answer": "羌族",
            "sex": "all",
            "number": "32",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "42",
            "subjectId": "5",
            "answer": "布朗族",
            "sex": "all",
            "number": "33",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "43",
            "subjectId": "5",
            "answer": "撒拉族",
            "sex": "all",
            "number": "34",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "44",
            "subjectId": "5",
            "answer": "毛南族",
            "sex": "all",
            "number": "35",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "45",
            "subjectId": "5",
            "answer": "仡佬族",
            "sex": "all",
            "number": "36",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "46",
            "subjectId": "5",
            "answer": "锡伯族",
            "sex": "all",
            "number": "37",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "47",
            "subjectId": "5",
            "answer": "阿昌族",
            "sex": "all",
            "number": "38",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "48",
            "subjectId": "5",
            "answer": "普米族",
            "sex": "all",
            "number": "39",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "49",
            "subjectId": "5",
            "answer": "塔吉克族",
            "sex": "all",
            "number": "40",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "50",
            "subjectId": "5",
            "answer": "怒族",
            "sex": "all",
            "number": "41",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "51",
            "subjectId": "5",
            "answer": "乌孜别克族",
            "sex": "all",
            "number": "42",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "52",
            "subjectId": "5",
            "answer": "俄罗斯族",
            "sex": "all",
            "number": "43",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "53",
            "subjectId": "5",
            "answer": "鄂温克族",
            "sex": "all",
            "number": "44",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "54",
            "subjectId": "5",
            "answer": "德昂族",
            "sex": "all",
            "number": "45",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "55",
            "subjectId": "5",
            "answer": "保安族",
            "sex": "all",
            "number": "46",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "56",
            "subjectId": "5",
            "answer": "裕固族",
            "sex": "all",
            "number": "47",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "57",
            "subjectId": "5",
            "answer": "京族",
            "sex": "all",
            "number": "48",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "58",
            "subjectId": "5",
            "answer": "塔塔尔族",
            "sex": "all",
            "number": "49",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "59",
            "subjectId": "5",
            "answer": "独龙族",
            "sex": "all",
            "number": "50",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "60",
            "subjectId": "5",
            "answer": "鄂伦春族",
            "sex": "all",
            "number": "51",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "61",
            "subjectId": "5",
            "answer": "赫哲族",
            "sex": "all",
            "number": "52",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "62",
            "subjectId": "5",
            "answer": "门巴族",
            "sex": "all",
            "number": "53",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "63",
            "subjectId": "5",
            "answer": "珞巴族",
            "sex": "all",
            "number": "54",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "64",
            "subjectId": "5",
            "answer": "基诺族",
            "sex": "all",
            "number": "55",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "65",
            "subjectId": "5",
            "answer": "其他",
            "sex": "all",
            "number": "56",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        }],
        "isShow": "true"
    },
    {
        "id": "6",
        "title": "身  高",
        "tip": "",
        "sort": "60",
        "theme": "个人资料",
        "type": "essay",
        "parentId": "",
        "condition": "",
        "specialTipsPath": "",
        "answers": [],
        "isShow": "true"
    },
    {
        "id": "7",
        "title": "体  重",
        "tip": "",
        "sort": "70",
        "theme": "个人资料",
        "type": "essay",
        "parentId": "",
        "condition": "",
        "specialTipsPath": "",
        "answers": [],
        "isShow": "true"
    },
    {
        "id": "8",
        "title": "婚姻状况",
        "tip": "",
        "sort": "80",
        "theme": "个人资料",
        "type": "single",
        "parentId": "",
        "condition": "",
        "specialTipsPath": "",
        "answers": [{
            "id": "1",
            "subjectId": "8",
            "answer": "已婚（含同居）",
            "sex": "all",
            "number": "0",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "2",
            "subjectId": "8",
            "answer": "未婚",
            "sex": "all",
            "number": "1",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "82+373",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "3",
            "subjectId": "8",
            "answer": "丧偶",
            "sex": "all",
            "number": "2",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "4",
            "subjectId": "8",
            "answer": "离异",
            "sex": "all",
            "number": "3",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "5",
            "subjectId": "8",
            "answer": "其他",
            "sex": "all",
            "number": "4",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        }],
        "isShow": "true"
    },
    {
        "id": "9",
        "title": "文化程度",
        "tip": "",
        "sort": "90",
        "theme": "个人资料",
        "type": "single",
        "parentId": "",
        "condition": "",
        "specialTipsPath": "",
        "answers": [{
            "id": "74",
            "subjectId": "9",
            "answer": "小学及以下",
            "sex": "all",
            "number": "0",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "75",
            "subjectId": "9",
            "answer": "初中",
            "sex": "all",
            "number": "1",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "76",
            "subjectId": "9",
            "answer": "高中",
            "sex": "all",
            "number": "2",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "77",
            "subjectId": "9",
            "answer": "中专及技校",
            "sex": "all",
            "number": "3",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "78",
            "subjectId": "9",
            "answer": "大学本科/专科",
            "sex": "all",
            "number": "4",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "79",
            "subjectId": "9",
            "answer": "研究生及以上",
            "sex": "all",
            "number": "5",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        }],
        "isShow": "true"
    },
    {
        "id": "10",
        "title": "职  业",
        "tip": "",
        "sort": "100",
        "theme": "个人资料",
        "type": "single",
        "parentId": "",
        "condition": "",
        "specialTipsPath": "",
        "answers": [{
            "id": "80",
            "subjectId": "10",
            "answer": "国家公务员",
            "sex": "all",
            "number": "0",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "81",
            "subjectId": "10",
            "answer": "专业技术人员",
            "sex": "all",
            "number": "1",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "82",
            "subjectId": "10",
            "answer": "职员",
            "sex": "all",
            "number": "2",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "83",
            "subjectId": "10",
            "answer": "企业管理人员",
            "sex": "all",
            "number": "3",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "84",
            "subjectId": "10",
            "answer": "工人",
            "sex": "all",
            "number": "4",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "85",
            "subjectId": "10",
            "answer": "农民",
            "sex": "all",
            "number": "5",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "86",
            "subjectId": "10",
            "answer": "学生",
            "sex": "all",
            "number": "6",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "87",
            "subjectId": "10",
            "answer": "现役军人",
            "sex": "all",
            "number": "7",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "88",
            "subjectId": "10",
            "answer": "自由职业者",
            "sex": "all",
            "number": "8",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "89",
            "subjectId": "10",
            "answer": "个体经营者",
            "sex": "all",
            "number": "9",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "90",
            "subjectId": "10",
            "answer": "无业人员",
            "sex": "all",
            "number": "10",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "91",
            "subjectId": "10",
            "answer": "退(离)休人员",
            "sex": "all",
            "number": "11",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "92",
            "subjectId": "10",
            "answer": "其他",
            "sex": "all",
            "number": "12",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        }],
        "isShow": "true"
    },
    {
        "id": "11",
        "title": "医保类别",
        "tip": "",
        "sort": "110",
        "theme": "个人资料",
        "type": "single",
        "parentId": "",
        "condition": "",
        "specialTipsPath": "",
        "answers": [{
            "id": "93",
            "subjectId": "11",
            "answer": "城镇职工医保",
            "sex": "all",
            "number": "0",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "94",
            "subjectId": "11",
            "answer": "城镇居民医保",
            "sex": "all",
            "number": "1",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "95",
            "subjectId": "11",
            "answer": "新农合医保",
            "sex": "all",
            "number": "2",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "96",
            "subjectId": "11",
            "answer": "其他",
            "sex": "all",
            "number": "3",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        },
        {
            "id": "97",
            "subjectId": "11",
            "answer": "无",
            "sex": "all",
            "number": "4",
            "content": "",
            "ordinaryLink": "",
            "accurateLink": "",
            "depthLink": "",
            "nolink": "",
            "diseaseRisk": "",
            "riskFactors": "",
            "disease": "",
            "condition": ""
        }],
        "isShow": "true"
    }],
    "map": {},
    "key": ""
}